# Only the services section for Development
version: "3.8"
services:
  postgres:
    image: postgres:12.4-alpine
    env_file:
      - ".env"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:6.0-alpine
    env_file:
      - ".env"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data:rw
volumes:
  postgres-data:
  redis-data:
